// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type PrStatusEnum string

const (
	PrStatusEnumOPEN   PrStatusEnum = "OPEN"
	PrStatusEnumMERGED PrStatusEnum = "MERGED"
)

func (e *PrStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PrStatusEnum(s)
	case string:
		*e = PrStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for PrStatusEnum: %T", src)
	}
	return nil
}

type NullPrStatusEnum struct {
	PrStatusEnum PrStatusEnum `json:"pr_status_enum"`
	Valid        bool         `json:"valid"` // Valid is true if PrStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPrStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.PrStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PrStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPrStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PrStatusEnum), nil
}

type PrReviewerAssignment struct {
	AssignmentID string             `json:"assignment_id"`
	PrID         string             `json:"pr_id"`
	ReviewerID   string             `json:"reviewer_id"`
	AssignedAt   pgtype.Timestamptz `json:"assigned_at"`
	ReplacedBy   pgtype.Text        `json:"replaced_by"`
}

type PullRequest struct {
	PullRequestID   string             `json:"pull_request_id"`
	PullRequestName string             `json:"pull_request_name"`
	AuthorID        string             `json:"author_id"`
	Status          NullPrStatusEnum   `json:"status"`
	MergedAt        pgtype.Timestamptz `json:"merged_at"`
}

type User struct {
	UserID   string `json:"user_id"`
	Username string `json:"username"`
	IsActive bool   `json:"is_active"`
	TeamName string `json:"team_name"`
}
