// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	AssignReviewer(ctx context.Context, arg AssignReviewerParams) (PrReviewerAssignment, error)
	CreatePR(ctx context.Context, arg CreatePRParams) (PullRequest, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetTeam(ctx context.Context, teamName string) ([]User, error)
	GetUser(ctx context.Context, userID string) (User, error)
	SetUserActivity(ctx context.Context, arg SetUserActivityParams) (User, error)
	TeamExists(ctx context.Context, teamName string) (bool, error)
}

var _ Querier = (*Queries)(nil)
