// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"
)

const assignReviewer = `-- name: AssignReviewer :one
INSERT INTO pr_reviewer_assignment (pr_id, reviewer_id)
VALUES ($1, $2)
RETURNING assignment_id, pr_id, reviewer_id, assigned_at, replaced_by
`

type AssignReviewerParams struct {
	PrID       string `json:"pr_id"`
	ReviewerID string `json:"reviewer_id"`
}

func (q *Queries) AssignReviewer(ctx context.Context, arg AssignReviewerParams) (PrReviewerAssignment, error) {
	row := q.db.QueryRow(ctx, assignReviewer, arg.PrID, arg.ReviewerID)
	var i PrReviewerAssignment
	err := row.Scan(
		&i.AssignmentID,
		&i.PrID,
		&i.ReviewerID,
		&i.AssignedAt,
		&i.ReplacedBy,
	)
	return i, err
}

const createPR = `-- name: CreatePR :one
INSERT INTO pull_requests (pull_request_id, pull_request_name, author_id)
VALUES ($1, $2, $3)
ON CONFLICT (pull_request_id) DO NOTHING
RETURNING pull_request_id, pull_request_name, author_id, status, merged_at
`

type CreatePRParams struct {
	PullRequestID   string `json:"pull_request_id"`
	PullRequestName string `json:"pull_request_name"`
	AuthorID        string `json:"author_id"`
}

func (q *Queries) CreatePR(ctx context.Context, arg CreatePRParams) (PullRequest, error) {
	row := q.db.QueryRow(ctx, createPR, arg.PullRequestID, arg.PullRequestName, arg.AuthorID)
	var i PullRequest
	err := row.Scan(
		&i.PullRequestID,
		&i.PullRequestName,
		&i.AuthorID,
		&i.Status,
		&i.MergedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (user_id, username, is_active, team_name)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE
SET 
    username = EXCLUDED.username,
    is_active = EXCLUDED.is_active,
    team_name = EXCLUDED.team_name
RETURNING user_id, username, is_active, team_name
`

type CreateUserParams struct {
	UserID   string `json:"user_id"`
	Username string `json:"username"`
	IsActive bool   `json:"is_active"`
	TeamName string `json:"team_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.UserID,
		arg.Username,
		arg.IsActive,
		arg.TeamName,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.IsActive,
		&i.TeamName,
	)
	return i, err
}

const getTeam = `-- name: GetTeam :many
SELECT user_id, username, is_active, team_name FROM users
WHERE team_name = $1
`

func (q *Queries) GetTeam(ctx context.Context, teamName string) ([]User, error) {
	rows, err := q.db.Query(ctx, getTeam, teamName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.IsActive,
			&i.TeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT user_id, username, is_active, team_name FROM users
WHERE user_id = $1
`

func (q *Queries) GetUser(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.IsActive,
		&i.TeamName,
	)
	return i, err
}

const setUserActivity = `-- name: SetUserActivity :one
UPDATE users
SET is_active = $2
WHERE user_id = $1
RETURNING user_id, username, is_active, team_name
`

type SetUserActivityParams struct {
	UserID   string `json:"user_id"`
	IsActive bool   `json:"is_active"`
}

func (q *Queries) SetUserActivity(ctx context.Context, arg SetUserActivityParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserActivity, arg.UserID, arg.IsActive)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.IsActive,
		&i.TeamName,
	)
	return i, err
}

const teamExists = `-- name: TeamExists :one
SELECT EXISTS (
  SELECT 1 FROM users WHERE team_name = $1
)
`

func (q *Queries) TeamExists(ctx context.Context, teamName string) (bool, error) {
	row := q.db.QueryRow(ctx, teamExists, teamName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
